apiVersion: v1
kind: PersistentVolume
metadata:
  name: "nextcloud-store"
  labels:
    type: "local"
spec:
  storageClassName: "nfs"
  capacity:
    storage: "10Gi"
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/ssd/nextcloud"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: "nextcloud"
  name: "nextcloud"
spec:
  storageClassName: "nfs"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "10Gi"
---