- job_name: "monitoring/arm-exporter"
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  kubernetes_sd_configs:
    - role: endpoints
      namespaces:
        names:
          - monitoring
  relabel_configs:
    - source_labels: [__meta_kubernetes_endpoints_name]
      regex: "arm-exporter"
      action: keep
    - source_labels: [__meta_kubernetes_endpoint_node_name]
      target_label: instance
